@startuml
namespace client {
    class Client4GUI implements common.ChatIF{
        __ private fields__
        -JTextField textField
        -JTextArea textArea
        __public methods__
        +display(String)
        +update(Observable, Object)
        +actionPerformed(ActionEvent)
    }
    abstract class ClientCommand {
        -String myString
        -Client4CommandProcessor myClient
        #String getStr()
        +doCommand()
    }
    abstract class NotConnectedClientCommand --|> ClientCommand
    class list --|> ClientCommand
    class logout -left-|> ClientCommand
    class quit -up-|> ClientCommand
    class whisper -up-|> ClientCommand
    class join -right-|> ClientCommand
    class getport --|> ClientCommand
    class gethost --|> ClientCommand
    class sethost --|> NotConnectedClientCommand
    class setport -down-|> NotConnectedClientCommand
    class login -up-|> NotConnectedClientCommand
}
namespace common{
    interface ChatIF
}
namespace ocsf{
    namespace ocsf.server{
        class AdaptableServer -up-|> AbstractServer
        class ObservableOriginatorServer -up-|> ObservableServer
        class ObservableServer
        abstract class AbstractServer
    }
    namespace ocsf.client{
        class ObservableClient
        class ObservableSWRClient -up-|> ObservableClient
    }
}
namespace server{
    namespace command{
        abstract class ServerCommand
        class close -left-|> ServerCommand
        class getport -up-|> ServerCommand
        class quit --|> ServerCommand
        class setport -up-|> ServerCommand
        class start -|> ServerCommand
        class stop -down-|> ServerCommand
    }    
    class Server4Console
   ' class ChannelManager
    class blockingHandler --|> ServerNonLoginHandler
    class Chat4Server -right|> ocsf.server.AbstractServer
    class JoinChannel -up-|> ServerNonLoginHandler
    class ListChannelHandler -|> ServerNonLoginHandler
    class PrivateMessageHandler -left-|> ServerNonLoginHandler
    class ServerLoginHandler -down-|> ServerMessageHandler
    class ServerMessageHandler
    class ServerNonLoginHandler --|> ServerMessageHandler
    class ServerStringMessageHandler --|> ServerNonLoginHandler
    class unblockingHandler --|> ServerNonLoginHandler
    class UserListChannelHandler -up-|> ServerNonLoginHandler
}

class server.Server4Console .down....|> common.ChatIF 

class client.Client4GUI -up|> JPanel
class client.Client4GUI .up|> ActionListener
class client.Client4GUI .up|> Observer

class ocsf.client.ObservableClient -up|> Observable
class ocsf.server.ObservableServer -up|> Observable
class Observer ..|> Observable
@enduml
